In [3]:
pip install torchvision

  Using cached torchvision-0.13.1-cp37-cp37m-manylinux1_x86_64.whl (19.1 MB)
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 776.3/776.3 MB 920.9 kB/s eta 0:00:0000:0100:05
  Using cached idna-3.3-py3-none-any.whl (61 kB)
  Using cached certifi-2022.6.15-py3-none-any.whl (160 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.4/140.4 kB 3.2 MB/s eta 0:00:00a 0:00:01
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
wavebeat 0.0.1 requires cython, which is not installed.
wavebeat 0.0.1 requires madmom, which is not installed.
wavebeat 0.0.1 requires mir_eval, which is not installed.
wavebeat 0.0.1 requires pytorch_lightning==1.1.8, which is not installed.
wavebeat 0.0.1 requires torchaudio==0.7.2, which is not installed.
wavebeat 0.0.1 requires torch==1.7.1, but you have torch 1.12.1 which is incompatible.
waveb

In [1]:
!pip install pyyaml

  Using cached PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (682 kB)


In [4]:
import torchvision
from torchvision.models.resnet import resnet18

In [5]:
resnet = resnet18(pretrained=False, num_classes = 512)


/homes/ssv02/.venv/lib/python3.7/site-packages/torchvision/models/_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and will be removed in 0.15, "
/homes/ssv02/.venv/lib/python3.7/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)


In [1]:
import torch

In [28]:
x = torch.empty(1, 2, 2530025)
print(x.shape)

torch.Size([1, 2, 2530025])


In [32]:

x = torch.empty(1, 2, 512)
y = torch.empty(1, 5, 512)
emb = torch.cat((x, y), dim=1)
print(emb.shape)
emb = emb.squeeze()
print(emb.shape)

torch.Size([1, 7, 512])
torch.Size([7, 512])


In [ ]:
import torch
from torch import nn
x = torch.empty(7, 512)
m = nn.linear(7 * 512 , 14)

In [1]:
import torch
print(torch.pi)

3.141592653589793


In [2]:
from dataloader import MedleyDBDataLoader
from dataloader import MedleyDBDataset

import torch

In [9]:
from dataloader import MedleyDBDataLoader, MedleyDBDataset
dataset = MedleyDBDataset()
dataloader = MedleyDBDataLoader()

In [18]:
import torch
from dataloader import MedleyDBDataLoader, MedleyDBDataset
dataset = MedleyDBDataset()
dataloader = MedleyDBDataLoader(type = "train")
for i, (songname, mix, stems, params) in enumerate(dataloader):
    print("shapes of tensors", mix.shape, stems.shape, params.shape)
    print(songname)
    if(i == 5):
        break
   


TypeError: cannot unpack non-iterable NoneType object

In [ ]:
train_dataloader = MedleyDBDataLoader(type="train")
    # create a data loader
    #train_dataloader = dataset(type="train")
print("\nTraining data loaded")
print(len(train_dataloader))
    #print(train_dataloader)
for i, (songname, mix, stems, params) in enumerate(train_dataloader):

        # move to the default device
        print(i)
        print(songname)
        

In [20]:
#used this script to remove dir with no tracks from the dataset. In the first round of generation, I forgot to remove the dir of songs with no tracks

import os
import glob
dir = os.getcwd()
dir = os.path.dirname(dir)
print(dir)
data_dir = glob.glob(os.path.join(dir, "data", "*"))
print(data_dir)

for i, dir in enumerate(data_dir):
    songdir = glob.glob(os.path.join(dir, "*"))
    print(songdir)
    for j, song in enumerate(songdir):
        data = glob.glob(os.path.join(song, "*"))
        if(len(data) == 0):
            print("empty")
            os.rmdir(song)
# data_dir = "./data/"
# for dirs in os.listdir(data_dir):
#     print(dirs)

/homes/ssv02/mix_style_transfer
['/homes/ssv02/mix_style_transfer/data/test', '/homes/ssv02/mix_style_transfer/data/train']
['/homes/ssv02/mix_style_transfer/data/test/TablaBreakbeatScience_MoodyPlucks', '/homes/ssv02/mix_style_transfer/data/test/Meaxic_YouListen', '/homes/ssv02/mix_style_transfer/data/test/AvaLuna_Waterduct', '/homes/ssv02/mix_style_transfer/data/test/MusicDelta_ChineseChaoZhou', '/homes/ssv02/mix_style_transfer/data/test/BigTroubles_Phantom', '/homes/ssv02/mix_style_transfer/data/test/MusicDelta_ChineseXinJing', '/homes/ssv02/mix_style_transfer/data/test/KarimDouaidy_Hopscotch', '/homes/ssv02/mix_style_transfer/data/test/MusicDelta_FusionJazz', '/homes/ssv02/mix_style_transfer/data/test/TablaBreakbeatScience_CaptainSky', '/homes/ssv02/mix_style_transfer/data/test/MusicDelta_Grunge', '/homes/ssv02/mix_style_transfer/data/test/HezekiahJones_BorrowedHeart', '/homes/ssv02/mix_style_transfer/data/test/Snowmine_Curfews', '/homes/ssv02/mix_style_transfer/data/test/MusicDelt

In [7]:
import os
import glob
import torch
import torchaudio


 

In [ ]:
data_dir = "/import/c4dm-datasets/MUSDB18HQ"
train_dir = os.path.join(data_dir, "train")
test_dir = os.path.join(data_dir, "test")
train_songs =  glob.glob(os.path.join(train_dir, "*"))
test_songs =  glob.glob(os.path.join(test_dir, "*"))
print(len(train_songs))
print(len(test_songs))
# for i, songdir in enumerate(songsdirs):

#     if i < 1: 
#         tracks = glob.glob(os.path.join(songdir, "*"))
#         for j, track in enumerate(tracks):
#             print(track)
#             mix, sr = torchaudio.load(track)
#             print(mix.shape)
#             print(sr)
            
#     i += 1    

: 

In [12]:
from dataloader import MUSEDB_on_the_fly, MedleyDBDataset
import numpy as np
from sklearn.model_selection import train_test_split
import torch
muse_dataset = MUSEDB_on_the_fly(type = "train")
medley_dataset = MedleyDBDataset(type = "train")
muse_dataloader = torch.utils.data.DataLoader(muse_dataset, batch_size=8, shuffle=True)
medley_dataloader = torch.utils.data.DataLoader(medley_dataset, batch_size=8, shuffle=True)

for i, (songname, mix, stems, params) in enumerate(muse_dataloader):
        print("shapes of tensors in musedb", mix.shape, stems.shape, params.shape)
        print(songname)
        if(i == 1):
                break
for i, (songname, mix, stems, params) in enumerate(medley_dataloader):
        print("shapes of tensors in medley", mix.shape, stems.shape, params.shape)
        print(songname)
        if(i == 1):
                break        

       
        
        # train_dataset = MUSEDB_on_the_fly(type = "train", idx =train_idx)
        # val_dataset = MUSEDB_on_the_fly(type = "val", idx = val_idx)
        
        # print("train_dataset", len(train_dataset))
        
        # print("val_dataset", len(val_dataset))

Found 100 songs in /import/c4dm-datasets/MUSDB18HQ/train.
Found 0 songs in ./datas/train.


ValueError: num_samples should be a positive integer value, but got num_samples=0

In [4]:

import torch
a = torch.rand(2,1,1)
b = torch.rand(2,1,1, 128)
print(a.shape)
print(b.shape)
c = a[:,None]*b
print(c.shape)

torch.Size([2, 1, 1])
torch.Size([2, 1, 1, 128])
torch.Size([2, 1, 1, 128])


In [6]:
import torch 
bs =1
track = 2
emb = 3
a = torch.rand(bs, track, emb)
print(a)
print(a.shape)
a = a.view(bs,track * emb) 
print(a.shape)
print(a)

tensor([[[0.2508, 0.3166, 0.8926],
         [0.8704, 0.7473, 0.4423]]])
torch.Size([1, 2, 3])
torch.Size([1, 6])
tensor([[0.2508, 0.3166, 0.8926, 0.8704, 0.7473, 0.4423]])


In [12]:
import torch
alpha = 10.0
a = torch.tensor([alpha])
print(a)

tensor([10.])


In [13]:
import torch
import torch.nn as nn
loss = nn.MSELoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5)
output = loss(input, target)
output.backward()
print(output)
print(type(output))
print(a*output)


tensor(1.8744, grad_fn=<MseLossBackward0>)
<class 'torch.Tensor'>
tensor([18.7445], grad_fn=<MulBackward0>)


In [ ]:
import torch
x = torch.randn(2, 512)
y = torch.randn(2, 512)
print(x.shape)
print(y.shape)
print(x.repeat(8,1,1).shape)

: 

In [ ]:
from torchsummary import summary
from model import *
import torch
import torch.nn as nn

model = encoder()
summary(model, [(8,2,22050),(8,4,1,22050)])

In [1]:
#Implementing diffcompressor from ChatGPT

import torch

class Compressor(torch.nn.Module):
    def __init__(self, threshold, ratio):
        super().__init__()
        self.threshold = threshold
        self.ratio = ratio

    def forward(self, x):
        # Compute the difference between the input and the threshold
        diff = x - self.threshold

        # Compress the signal using the ratio
        compressed = diff / self.ratio + self.threshold

        # Use the threshold to mask the compressed signal
        y = torch.where(x > self.threshold, compressed, x)

        return y


In [11]:
# Create a compressor with a threshold of 0.5 and a ratio of 2
compressor = Compressor(0.5, 2)

# Generate a test signal with a wide dynamic range
x = torch.ones(10)
x= x * 12
print(x)

# Compress the dynamic range of the signal
y = compressor(x)
print(y)


tensor([12., 12., 12., 12., 12., 12., 12., 12., 12., 12.])
tensor([6.2500, 6.2500, 6.2500, 6.2500, 6.2500, 6.2500, 6.2500, 6.2500, 6.2500,
        6.2500])


In [12]:
# Calculate the loss
loss = torch.mean((y - x) ** 2)
print(loss)

# Backpropagate the loss and calculate the gradients
#loss.backward()

tensor(33.0625)


In [ ]:

#get_item for medley_db_on the fly
def __getitem__(self, _):
        # This is in the case of off-the-go mix generation
        print(len(self.mix_dirs))
        # print(self.mix_dirs)
        # select a song directory at random
        # songdir = np.random.choice(self.songdirs)
        # print(songdir)
        # # get info
        # songname = os.path.basename(songdir)
        # print(songname)
        # stem_dir = os.path.join(songdir, songname + "_STEMS/")
        # print("stem_dir:", stem_dir)
        # filepaths = glob.glob(os.path.join(stem_dir, "*.wav"))
        # print("filepaths", filepaths)


        

        # # print(params.shape)
        # stems_orig = []
        # stems_rmix = []
        # # print(filepaths[0])
        # i = 0
        # for filepath in filepaths:
        #     if filepath.endswith(".wav"):
        #         md = torchaudio.info(filepath)
           
        #         # starting index for the original mix
        #         start_idx = random.randint(0, md.num_frames - self.sample_rate*self.duration - 1)
        #         #starting index for reference mix
        #         if self.diff_sections:
        #             rmix_sidx = random.randint(0, md.num_frames - self.sample_rate*self.duration - 1)
        #         #start_idx = 0
        #         print("start_idx:", start_idx)
        #         print("rmix_idx:", rmix_sidx)
        #         break
        # i = 0
        # for filepath in filepaths:


        #     # to be fast, just load the part of the audio you want

        #     # print(start_idx)
        #     if i < self.num_tracks:
        #         stem_orig, sr = torchaudio.load(
        #             filepath,
        #             frame_offset=start_idx,
        #             num_frames=self.duration * self.sample_rate,
        #         )
        #         print("filepath", filepath)
        #         #Convert Stereo to Mono
        #         if stem_orig.shape[0] == 2:
        #             stem_orig = stems_orig.mean(0, keepdim=True)
        #         stems_orig.append(stem_orig)
                


        #         # print("its stem",stem.shape)
        #         #load stems inn case we want to use different sections for mix and reference
        #         if self.diff_sections:
        #             stem_rmix, sr = torchaudio.load(
        #                 filepath,
        #                 frame_offset=rmix_sidx,
        #                 num_frames=self.duration * self.sample_rate,
        #             )
        #             if stem_rmix.shape[0] == 2:
        #                 stem_rmix = stems_rmix.mean(0, keepdim=True)
        #             stems_rmix.append(stem_rmix)
        #         i += 1
                

        # stems_orig = torch.stack(stems)
        # print("stems: ",stems_orig.shape)
        # # print("params:", params.shape)
        # # print("mix",mix.shape)

        # params = torch.rand(i,2)
        
        # params = params.unsqueeze(0)
        # stems_orig = stems_orig.unsqueeze(0)
        # print("params:", params.shape)
        # print("stems:", stems_orig.shape)
        # orig_mix = mix_gen(stems_orig, params)
        # print("orig_mix:", orig_mix.shape)
        # #initialize params

        # if self.diff_sections:
        #     stems_rmix = torch.stack(stems_rmix)
        #     params_rmix = torch.rand(i,2)
        #     params_rmix = params_rmix.unsqueeze(0)
        #     stems_rmix = stems_rmix.unsqueeze(0)
        #     rmix = mix_gen(stems_rmix, params_rmix)
        #     print("rmix:", rmix.shape)
            
        # else:
        #     rmix = orig_mix

        # stems_orig = stems_orig.squeeze(0)
        # orig_mix = orig_mix.squeeze(0)
        # rmix = rmix.squeeze(0)


        # return songname, stems_orig, orig_mix, rmix

ModuleNotFoundError: No module named 'pyyaml'

In [3]:
!pip install pyyaml

In [1]:
import os
import glob
#import pyyaml
meta_dir = "/homes/ssv02/style_transfer/mix_style_transfer/mst/dataloaders/medley_metadata"
if not os.path.exists(meta_dir):
    print("meta_dir does not exist")
print(meta_dir)
meta_file = glob.glob(os.path.join(meta_dir, "*"))
print(meta_file)

print(len(meta_file))

/homes/ssv02/style_transfer/mix_style_transfer/mst/dataloaders/medley_metadata
['/homes/ssv02/style_transfer/mix_style_transfer/mst/dataloaders/medley_metadata/TablaBreakbeatScience_WhoIsIt_METADATA.yaml', '/homes/ssv02/style_transfer/mix_style_transfer/mst/dataloaders/medley_metadata/ClaraBerryAndWooldog_Boys_METADATA.yaml', '/homes/ssv02/style_transfer/mix_style_transfer/mst/dataloaders/medley_metadata/MusicDelta_Gospel_METADATA.yaml', '/homes/ssv02/style_transfer/mix_style_transfer/mst/dataloaders/medley_metadata/SlowGhost_FirstSnow_METADATA.yaml', '/homes/ssv02/style_transfer/mix_style_transfer/mst/dataloaders/medley_metadata/SlowGhost_YoureAMystery_METADATA.yaml', '/homes/ssv02/style_transfer/mix_style_transfer/mst/dataloaders/medley_metadata/MusicDelta_Britpop_METADATA.yaml', '/homes/ssv02/style_transfer/mix_style_transfer/mst/dataloaders/medley_metadata/FacesOnFilm_WaitingForGa_METADATA.yaml', '/homes/ssv02/style_transfer/mix_style_transfer/mst/dataloaders/medley_metadata/JoelHe

In [28]:
os.path.basename(meta_file[0]).replace("_METADATA.yaml","")

'TheBeatles_YouWontSeeMe'

In [3]:
from yaml import load, dump
from yaml import Loader, Dumper

with open(meta_file[0], 'r') as stream:
    file = load(stream, Loader=Loader)
    print(file)
#print(file.values())
# DICT = {}

# DICT = file['stems']
# print(DICT)
#     #print(value)
# for key, value in DICT.items():
#     print(key, ":", value) 
    



#print(file['filename'])


{'album': 'Music Information Retrieval', 'artist': 'Tabla Breakbeat Science', 'composer': ['Ethan Hein'], 'excerpt': 'no', 'genre': 'Electronic/Fusion', 'has_bleed': 'no', 'instrumental': 'yes', 'mix_filename': 'TablaBreakbeatScience_WhoIsIt_MIX.wav', 'origin': 'Dolan Studio', 'producer': ['Ethan Hein'], 'raw_dir': 'TablaBreakbeatScience_WhoIsIt_RAW', 'stem_dir': 'TablaBreakbeatScience_WhoIsIt_STEMS', 'stems': {'S01': {'component': '', 'filename': 'TablaBreakbeatScience_WhoIsIt_STEM_01.wav', 'instrument': 'drum machine', 'raw': {'R01': {'filename': 'TablaBreakbeatScience_WhoIsIt_RAW_01_01.wav', 'instrument': 'drum machine'}, 'R02': {'filename': 'TablaBreakbeatScience_WhoIsIt_RAW_01_02.wav', 'instrument': 'drum machine'}}}, 'S02': {'component': '', 'filename': 'TablaBreakbeatScience_WhoIsIt_STEM_02.wav', 'instrument': 'synthesizer', 'raw': {'R01': {'filename': 'TablaBreakbeatScience_WhoIsIt_RAW_02_01.wav', 'instrument': 'synthesizer'}, 'R02': {'filename': 'TablaBreakbeatScience_WhoIsIt_

In [78]:
medley_dir = ["/import/c4dm-datasets/MedleyDB_V1/V1", "/import/c4dm-datasets/MedleyDB_V2/V2"]
mix_dirs = []
for path in medley_dir:
    mix_dir = glob.glob(os.path.join(path, "*"))
    print(len(mix_dir))
    mix_dirs.extend(mix_dir)
print(len(mix_dirs))

meta_dir = "/homes/ssv02/style_transfer/mix_style_transfer/mst/dataloaders/medley_metadata"
meta_file = glob.glob(os.path.join(meta_dir, "*"))
print(len(meta_file))
  

122
74
196
330


In [79]:
mix_id = [os.path.basename(mix_dir) for mix_dir in mix_dirs]
meta_id = [os.path.basename(meta).replace("_METADATA.yaml","") for meta in meta_file]
metadata = {meta_id[i]:meta_file[i] for i in range(len(meta_file))}
print(len(metadata))
print(len(mix_id))
       
        # for mix in mix_id:
        #     if mix in meta_id:
        #         filtered_meta[mix_id] = self.metadata[meta_id]

330
196


In [ ]:
for meta in meta_id:
    if meta not in mix_id:
        os.remove(metadata[meta])